#!/usr/bin/env python3
"""Generate a PaperweightOS fastfetch theme file from a sway theme palette.

fastfetch doesn't accept raw hex in its jsonc color fields — it wants ANSI
SGR parameter strings (e.g. "1;38;2;138;173;244" for bold truecolor). This
reads the 26-variable palette already defined in a sway theme file (the
canonical source per THEME-AUTHORING.md) and emits a matching
~/.config/fastfetch/themes/<name>.jsonc, so a new theme's fastfetch colors
never have to be hand-converted or re-typed.

Usage:
    ./fastfetch-theme-gen.py <name> [--label "Display Name"]
    ./fastfetch-theme-gen.py macchiato
    ./fastfetch-theme-gen.py sunset --label "Sunset"

    # Convert a single hex color to fastfetch's SGR format, e.g. for
    # spot-checking a value or using in a hand-written jsonc file:
    ./fastfetch-theme-gen.py --hex 8aadf4 --bold

By default reads from and writes to the packaging tree paths used by
paperweight-skel:
    packaging/paperweight-skel/etc/skel/.config/sway/themes/<name>.conf
    packaging/paperweight-skel/etc/skel/.config/fastfetch/themes/<name>.jsonc
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SKEL_CONFIG = REPO_ROOT / "packaging" / "paperweight-skel" / "etc" / "skel" / ".config"
SWAY_THEMES = SKEL_CONFIG / "sway" / "themes"
FASTFETCH_THEMES = SKEL_CONFIG / "fastfetch" / "themes"

# Maps the fastfetch theme's semantic roles to sway palette variable names.
# See THEME-AUTHORING.md's "26 palette variables" table.
ROLES = {
    "lavender": "lavender",
    "blue": "blue",
    "overlay1": "overlay1",
    "surface2": "surface2",
    "text": "text",
    "green": "green",
    "yellow": "yellow",
    "red": "red",
}

TEMPLATE = """// PaperweightOS fastfetch theme — {label}
// Generated by fastfetch-theme-gen.py from sway/themes/{name}.conf.
// Written by paperweight-theme at runtime; edit this file (or the sway
// palette + regenerate), not the live ~/.config/fastfetch/config.jsonc.
{{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {{
        "type": "small",
        "padding": {{ "top": 1 }},
        "color": {{ "1": "{lavender_bold}" }}
    }},
    "display": {{
        "separator": " ",
        "key": {{ "width": 8 }},
        "color": {{
            "keys": "{lavender_bold}",
            "output": "{text}",
            "separator": "{surface2}"
        }},
        "percent": {{
            "color": {{
                "green": "{green}",
                "yellow": "{yellow}",
                "red": "{red}"
            }}
        }}
    }},
    "modules": [
        {{
            "type": "title",
            "color": {{ "user": "{blue_bold}", "at": "{overlay1}", "host": "{lavender_bold}" }}
        }},
        "separator",
        {{ "type": "os", "key": "OS" }},
        {{ "type": "kernel", "key": "Kernel" }},
        {{ "type": "uptime", "key": "Uptime" }},
        {{ "type": "cpu", "key": "CPU" }},
        {{ "type": "memory", "key": "Memory" }},
        {{ "type": "disk", "folders": "/", "key": "Disk" }},
        {{ "type": "localip", "defaultRouteOnly": true, "key": "IP" }},
        {{ "type": "battery", "key": "Battery" }}
    ]
}}
"""

HEX_RE = re.compile(r"^#?([0-9a-fA-F]{6})$")


def hex_to_sgr(hexval: str, bold: bool = False) -> str:
    """Convert a #rrggbb color to a fastfetch truecolor SGR string."""
    m = HEX_RE.match(hexval.strip())
    if not m:
        raise ValueError(f"not a 6-digit hex color: {hexval!r}")
    h = m.group(1)
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    prefix = "1;" if bold else ""
    return f"{prefix}38;2;{r};{g};{b}"


def parse_sway_palette(conf_path: Path) -> dict[str, str]:
    """Parse `set $name #hexhex` lines out of a sway theme file."""
    palette = {}
    line_re = re.compile(r"^\s*set\s+\$(\w+)\s+(#[0-9a-fA-F]{6})\s*$")
    for line in conf_path.read_text().splitlines():
        m = line_re.match(line)
        if m:
            palette[m.group(1)] = m.group(2)
    return palette


def guess_label(conf_path: Path, name: str) -> str:
    """Pull a display label from the theme file's leading comment, if any."""
    first_line = conf_path.read_text().splitlines()[0] if conf_path.exists() else ""
    m = re.match(r"#\s*(.+?)\s*—", first_line)
    if m:
        return m.group(1)
    return name.capitalize()


def generate(name: str, label: str | None, sway_dir: Path, out_dir: Path) -> Path:
    conf_path = sway_dir / f"{name}.conf"
    if not conf_path.is_file():
        sys.exit(f"error: no sway theme found at {conf_path}")

    palette = parse_sway_palette(conf_path)
    missing = [var for var in ROLES.values() if var not in palette]
    if missing:
        sys.exit(f"error: {conf_path} is missing palette variable(s): {', '.join(missing)}")

    label = label or guess_label(conf_path, name)

    content = TEMPLATE.format(
        name=name,
        label=label,
        lavender_bold=hex_to_sgr(palette["lavender"], bold=True),
        blue_bold=hex_to_sgr(palette["blue"], bold=True),
        overlay1=hex_to_sgr(palette["overlay1"]),
        surface2=hex_to_sgr(palette["surface2"]),
        text=hex_to_sgr(palette["text"]),
        green=hex_to_sgr(palette["green"]),
        yellow=hex_to_sgr(palette["yellow"]),
        red=hex_to_sgr(palette["red"]),
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{name}.jsonc"
    out_path.write_text(content)
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("name", nargs="?", help="theme name, e.g. macchiato (matches sway/themes/<name>.conf)")
    parser.add_argument("--label", help="display label for the generated file's header comment")
    parser.add_argument("--sway-dir", type=Path, default=SWAY_THEMES, help="directory containing sway theme .conf files")
    parser.add_argument("--out-dir", type=Path, default=FASTFETCH_THEMES, help="directory to write the fastfetch theme .jsonc into")
    parser.add_argument("--hex", help="convert a single #rrggbb color to fastfetch SGR format and exit")
    parser.add_argument("--bold", action="store_true", help="with --hex, emit the bold variant")
    args = parser.parse_args()

    if args.hex:
        print(hex_to_sgr(args.hex, bold=args.bold))
        return

    if not args.name:
        parser.error("name is required unless --hex is given")

    out_path = generate(args.name, args.label, args.sway_dir, args.out_dir)
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
